### ISSUE TITLE
HSV To RGB not returning black

### ISSUE THREAD

**Issue by davewilton** [iamartyom/ColorHelper#1]
I'm happy to add a test for this next week if it helps. I wanted to check though, I don't think I'm doing anything wrong? I'm getting white back when I expect black

![image](https://user-images.githubusercontent.com/2278405/101868852-4f079500-3bd2-11eb-8793-f934f6a4c071.png)

**Comment by davewilton** [comment]
Created pull request.  https://github.com/iamartyom/ColorHelper/pull/2

**Comment by ryno1234** [comment]
I'm experiencing the same except I'm receiving it when converting from HSV to HEX.

**Comment by Tum4ik** [comment]
yeah, the same... if saturation or value is zero, then it results in a white color.

**Comment by iamartyom** [comment]
This problem was fixed in version 1.6.2.
