### ISSUE TITLE
BakerMillerPink is causing an exception.

### ISSUE THREAD

**Issue by lyssieth** [iamartyom/ColorHelper#7]
This seems to be a missing case in your `switch` statement.

I'm iterating over all values of ColorName because I'm using it to find the nearest color name for a user-input color.

**Comment by lyssieth** [comment]
The issue is at https://github.com/iamartyom/ColorHelper/blob/95321f41495b17473ddef5c8b452c857e26a4049/ColorHelper/Color/ColorNames.cs#L1032-L1035

**Comment by lyssieth** [comment]
It's the only one missing as far as I can tell.

**Comment by iamartyom** [comment]
Hi @lyssieth.

Thanks for your contributing.

I will merge your changes and create new release now with version 1.6.1.
